# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Fri Nov  3 14:43:28 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class wxWarningDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxWarningDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Warning")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.label_title = wx.StaticText(self, wx.ID_ANY, "Warning:")
        self.label_title.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(self.label_title, 0, wx.ALL, 5)

        self.label_message = wx.StaticText(self, wx.ID_ANY, "This is a test message. Pick an option below.")
        self.label_message.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(self.label_message, 0, wx.ALL, 5)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.Hide()
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_YES = wx.Button(self, wx.ID_YES, "")
        self.button_YES.Hide()
        sizer_2.AddButton(self.button_YES)

        self.button_NO = wx.Button(self, wx.ID_NO, "")
        self.button_NO.Hide()
        sizer_2.AddButton(self.button_NO)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_NO.GetId())

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.on_yesOk, self.button_OK)
        self.Bind(wx.EVT_BUTTON, self.on_yesOk, self.button_YES)
        self.Bind(wx.EVT_BUTTON, self.on_noCancel, self.button_NO)
        # end wxGlade

    def on_yesOk(self, event):  # wxGlade: wxWarningDialog.<event_handler>
        print("Event handler 'on_yesOk' not implemented!")
        event.Skip()

    def on_noCancel(self, event):  # wxGlade: wxWarningDialog.<event_handler>
        print("Event handler 'on_noCancel' not implemented!")
        event.Skip()

# end of class wxWarningDialog
